export default [
  // Vertragsdaten
  'Transaktionsgrund',
  'Einzugsdatum',
  'Vertragsbindung bei Vorlieferant',
  'Wunschtermin',
  'Datum Vertragseingang',
  'Typ Vertrag',
  'Kunde zahlt Netznutzung',
  'Bilanzkreis',
  // Stammdaten
  'VIP',
  'Kundenart',
  // Masterkunde - sonstiges
  'Schreiben an Masterkunden adressieren (postalisch)',
  'Schreiben an MP elektronisch',
  'Abschläge und Verbräuche summieren',
  'Abschläge auch bei untergeordneten Kunden buchen',
  'Abschläge sind nur bei untergeordnetem Kunden abbuchbar',
  'MK Abschlagsplan',
  'Versandart des Masters verwenden',
  'E-Mailadresse des Masters verwenden',
  // Rechnungsanschrift
  'RA Identnummer',
  'RA Master_ID',
  'RA Firma',
  'RA Abteilung',
  'RA c/o bei Firma',
  'RA Briefanrede',
  'RA Anrede',
  'RA Amts- Berufsbezeichnung',
  'RA Titel',
  'RA Vorname',
  'RA Nachname',
  'RA Anrede2',
  'RA Titel2',
  'RA Vorname2',
  'RA Nachname2',
  'RA Geburtstag',
  'RA Geburtstag2',
  'RA Straße',
  'RA Hausnummer',
  'RA Hausnummerergänzung',
  'RA Wohnungs-Nr.',
  'RA Stock',
  'RA Postleitzahl',
  'RA Ort',
  'RA Teilort',
  'RA Land',
  'RA Telefon privat',
  'RA Fax',
  'RA Telefon geschäftlich',
  'RA Mobil',
  'RA E-Mailadresse',
  'RA Login',
  'RA Passwort',
  'Interne ID',
  'Versandart',
  // Zusätzliche Mailadressen
  'alle Kundenschreiben',
  'Abrechnung',
  'Mahnung',
  'Mitteilung',
  'Lastgangdaten',
  // Bankdaten
  'RA Kontoinhaber',
  'RA Bank',
  'RA BIC',
  'RA IBAN',
  'RA Mandat-Nr.',
  'RA Datum Unterschrift',
  'RA einmalige Zahlung',
  'RA Firmenmandat',
  'RA elektronisches Mandat',
  'RA Selbstzahler',
  'RA Zahlungstermin',
  'RA Zusätzlicher DTA Verwendungszweck',
  // falls Kontoinhaber abweichend
  'AKI Anrede Zahler',
  'AKI Amts- Berufsbezeichnung',
  'AKI Titel Zahler',
  'AKI Vorname Zahler',
  'AKI Nachname Zahler',
  'AKI Firma Zahler',
  'AKI Abteilung',
  'AKI c/o Zusatz Zahler',
  'AKI Straße Zahler',
  'AKI Hausnummer Zahler',
  'AKI Hausnummerergänzung Zahler',
  'AKI Wohnungs-Nr.',
  'AKI Stock',
  'AKI PLZ Zahler',
  'AKI Ort Zahler',
  'AKI Teilort',
  'AKI Land Zahler',
  'AKI Telefon Privat Zahler',
  'AKI Telefon geschäftlich Zahler',
  'AKI Mobil Zahler',
  'AKI Fax Zahler',
  'AKI E-Mail Zahler',
  // Leistungsempfänger
  'LE Firma',
  'LE Abteilung',
  'LE c/o Zusatz',
  'LE Straße',
  'LE Hausnummer',
  'LE Hausnummerergänzung',
  'LE Wohnungs-Nr.',
  'LE Stock',
  'LE PLZ',
  'LE Ort',
  'LE Teilort',
  'LE Land',
  // Vollmacht Datenschutz
  'VM_Vorname',
  'VM_Nachname',
  'VM_Firma',
  'VM_Straße',
  'VM_Hausnummer',
  'VM_Hausnummerergänzung',
  'VM_Wohnungs-Nr.',
  'VM_Stock',
  'VM_PLZ',
  'VM_Ort',
  'VM_Teilort',
  'VM_Geburtsdatum',
  'VM_Änderung',
  // Lieferstelle (LS)
  'LS Vorname',
  'LS Nachname',
  'LS Firma',
  'LS-Namenszusatz',
  'Lieferstellenbezeichnung',
  'LS Straße',
  'LS Hausnummer',
  'LS Hausnummerergänzung',
  'LS Wohnungs-Nr.',
  'LS Stock',
  'LS PLZ',
  'LS Ort',
  'LS Teilort',
  'LS Bundesland',
  'Kostenstelle',
  'Vormieter',
  'Umgezogen von',
  // Zählerdaten
  'Zählernummer',
  'MaLo-ID',
  'MeLo-ID',
  'Verbrauch kWh/a HT',
  'Verbrauch kWh/a NT',
  'Zählverfahren',
  'Abschlag',
  'Abschlagsplan',
  'bisherige Jahresmaximalleistung',
  'Zähleranfang (HT)',
  'Zähleranfang (NT)',
  'Ablesedatum',
  'Ableseart',
  'Konzessionsabgabe',
  'Konzessionsabgabe Betrag (€/kWh)',
  'Konzessionsabgabe Schwachlast',
  'Konzessionsabgabe Betrag SL (€/kWh)',
  'Gemeinderabatt (in%)',
  // Angaben Marktpartner
  'bisheriger Lieferant',
  'Kundennummer bei Altlieferant',
  'Verteilnetzbetreiber',
  // Weitere Daten
  'Handelsvertreter / VM Nr.',
  'ID Berater',
  'Partner',
  'Ramenvertragskunde',
  'Umsatzsteuer-ID',
  'Erlaubnisschein Nr.',
  'Erlaubnisschein Nr. gültig ab',
  'Steuerliche Bewertung',
  // Vermittlungen
  'DVK Nr.',
  'VA-Nr.',
  'Ordercode',
  'vermittelt durch',
  // Prämien
  'Geworbener Identnummer',
  'Geworbener Prämie/Bonus in Euro',
  'Geworbener Prämie/Bonus in kWh',
  'Geworbener Sachprämie',
  'Geworbener Termin der Auszahlung Prämie/Bonus',
  'Geworbener Prämienart',
  'Geworbener Auszahlungsdatum',
  'Werber Identnummer',
  'Werber Prämie/Bonus in Euro',
  'Werber Prämie/Bonus in kWh',
  'Werber Sachprämie',
  'Werber Termin der Auszahlung Prämie/Bonus',
  'Werber Prämienart',
  'Werber Auszahlungsdatum',
  'Bemerkung Prämie',
  /** Stromtarife **/
  // Sonstige Daten
  'Werbung',
  'Kategorie bei NN',
  'Kundengruppe',
  'Ansprechpartner Vertrieb',
  'Abrechnungszeitpunkt',
  'Abrechnungsplan',
  'Zahlungsziel Abrechnung',
  'Bemerkung',
  // Stammdaten Tarif - Pflichtfelder
  'T-ID',
  'Partner',
  'gültig_ab',
  // Stammdaten Tarif
  'gültig_bis',
  'Preisgarantie bis (Datum)',
  'Preisgarantie in Monate',
  'Bezeichnung_extern',
  'Bezeichnung_intern',
  'Tarifart',
  // Preisangaben - Standard- bzw. Energiepreis
  'monatlicher Grundpreis netto',
  'Arbeitspreis_HT excl. Stromsteuer und USt',
  'Arbeitspreis_NT excl. Stromsteuer und USt',
  // Preisangaben - Netznutzung
  'Grundpreis Netznutzung/netto',
  'Arbeitspreis_HT Netznutzung/netto',
  'Arbeitspreis_NT Netznutzung/netto',
  'Abrechnungspreis',
  'Messpreis',
  'Messstellenbetrieb',
  // Steuerangaben - Pflichtfelder
  'Stromsteuer_HT',
  'Stromsteuer_NT',
  'USt %',
  // Tarifangaben - sonstiges
  'Kaution',
  'Gebührenart',
  'Gebühr',
  // Umlage - Standard- Energiepreis
  'EEG ct/kWh',
  // Umlagen - Netznutzung
  'Abschaltbare Lasten ct/kWh',
  'KWKG ct/kWh',
  'NEV_Umlage ct/kWh',
  'Offshore Netzumlage ct/kWh',
  'Konzessionsabgabe_HT',
  'Konzessionsabgabe_Zone_HT',
  'Konzessionsabgabe_HT gezont',
  'Konzessionsabgabe_NT',
  'Konzessionsabgabe_Zone_NT',
  'Konzessionsabgabe_NT gezont',
  // Stammdaten Tarif
  'Mindestvertragslaufzeit',
  'Folgelaufzeit in Monaten einmalig',
  'Folgelaufzeit in Monaten regelmäßig',
  'Kündigungsfrist',
  // Tarifangaben - sonstiges
  'Bemerkung / Tarifstaffel / Info / Freifeld',
  // Preisangaben Netznutzung - RLM
  'Leistungspreis_monatlich',
  'Leistungspreis_jährlich',
  'Blindmehrarbeit',
  // Staffel-/Zonenpreise
  'HT-Staffel 1 von kWh',
  'HT-Staffel 1 bis kWh',
  'HT-Staffel 1 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 1 ct/kWh netto ohne USt',
  'HT-Staffel 2 von kWh',
  'HT-Staffel 2 bis kWh',
  'HT-Staffel 2 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 2 ct/kWh netto ohne USt',
  'HT-Staffel 3 von kWh',
  'HT-Staffel 3 bis kWh',
  'HT-Staffel 3 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 3 ct/kWh netto ohne USt',
  'HT-Staffel 4 von kWh',
  'HT-Staffel 4 bis kWh',
  'HT-Staffel 4 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 4 ct/kWh netto ohne USt',
  'HT-Staffel 5 von kWh',
  'HT-Staffel 5 bis kWh',
  'HT-Staffel 5 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 5 ct/kWh netto ohne USt',
  'HT-Staffel 6 von kWh',
  'HT-Staffel 6 bis kWh',
  'HT-Staffel 6 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 6 ct/kWh netto ohne USt',
  'HT-Staffel 7 von kWh',
  'HT-Staffel 7 bis kWh',
  'HT-Staffel 7 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 7 ct/kWh netto ohne USt',
  'HT-Staffel 8 von kWh',
  'HT-Staffel 8 bis kWh',
  'HT-Staffel 8 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 8 ct/kWh netto ohne USt',
  'HT-Staffel 9 von kWh',
  'HT-Staffel 9 bis kWh',
  'HT-Staffel 9 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 9 ct/kWh netto ohne USt',
  'NT-Staffel 1 von kWh',
  'NT-Staffel 1 bis kWh',
  'NT-Staffel 1 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 1 ct/kWh netto ohne USt',
  'NT-Staffel 2 von kWh',
  'NT-Staffel 2 bis kWh',
  'NT-Staffel 2 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 2 ct/kWh netto ohne USt',
  'NT-Staffel 3 von kWh',
  'NT-Staffel 3 bis kWh',
  'NT-Staffel 3 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 3 ct/kWh netto ohne USt',
  'NT-Staffel 4 von kWh',
  'NT-Staffel 4 bis kWh',
  'NT-Staffel 4 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 4 ct/kWh netto ohne USt',
  'NT-Staffel 5 von kWh',
  'NT-Staffel 5 bis kWh',
  'NT-Staffel 5 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 5 ct/kWh netto ohne USt',
  'NT-Staffel 6 von kWh',
  'NT-Staffel 6 bis kWh',
  'NT-Staffel 6 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 6 ct/kWh netto ohne USt',
  'NT-Staffel 7 von kWh',
  'NT-Staffel 7 bis kWh',
  'NT-Staffel 7 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 7 ct/kWh netto ohne USt',
  'NT-Staffel 8 von kWh',
  'NT-Staffel 8 bis kWh',
  'NT-Staffel 8 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 8 ct/kWh netto ohne USt',
  'NT-Staffel 9 von kWh',
  'NT-Staffel 9 bis kWh',
  'NT-Staffel 9 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 9 ct/kWh netto ohne USt',
  'Zonenpreise ja/nein',
];
