export default [
  'Transaktionsgrund',
  'Einzugsdatum',
  'Vertragsbindung bei Vorlieferant',
  'Wunschtermin',
  'Datum Vertragseingang',
  'Typ Vertrag',
  'Kunde zahlt Netznutzung',
  'Bilanzkreis',
  'VIP',
  'Kundenart',
  'Schreiben an Masterkunden adressieren (postalisch)',
  'Schreiben an MP elektronisch',
  'Abschläge und Verbräuche summieren',
  'Abschläge auch bei untergeordneten Kunden buchen',
  'Abschläge sind nur bei untergeordnetem Kunden abbuchbar',
  'MK Abschlagsplan',
  'Versandart des Masters verwenden',
  'E-Mailadresse des Masters verwenden',
  'RA Identnummer',
  'RA Master_ID',
  'RA Firma',
  'RA c/o bei Firma',
  'RA Briefanrede',
  'RA Anrede',
  'RA Titel',
  'RA Vorname',
  'RA Nachname',
  'RA Anrede2',
  'RA Titel2',
  'RA Vorname2',
  'RA Nachname2',
  'RA Geburtstag',
  'RA Geburtstag2',
  'RA Straße',
  'RA Hausnummer',
  'RA Hausnummerergänzung',
  'RA Postleitzahl',
  'RA Ort',
  'RA Land',
  'RA Telefon privat',
  'RA Fax',
  'RA Telefon geschäftlich',
  'RA Mobil',
  'RA E-Mailadresse',
  'RA Login',
  'RA Passwort',
  'Interne ID',
  'Versandart',
  'RA Kontoinhaber',
  'RA Bank',
  'RA BIC',
  'RA IBAN',
  'RA Mandat-Nr.',
  'RA Datum Unterschrift',
  'RA einmalige Zahlung',
  'RA Firmenmandat',
  'RA elektronisches Mandat',
  'RA Selbstzahler',
  'RA Zahlungstermin',
  'RA Zusätzlicher DTA Verwendungszweck',
  'RA Anrede Zahler',
  'RA Titel Zahler',
  'RA Vorname Zahler',
  'RA Nachname Zahler',
  'RA Firma Zahler',
  'RA c/o Zusatz Zahler',
  'RA Straße Zahler',
  'RA Hausnummer Zahler',
  'RA Hausnummerergänzung Zahler',
  'RA PLZ Zahler',
  'RA Ort Zahler',
  'RA Land Zahler',
  'RA Telefon Privat Zahler',
  'RA Telefon geschäftlich Zahler',
  'RA Mobil Zahler',
  'RA Fax Zahler',
  'RA E-Mail Zahler',
  'Firma',
  'c/o Zusatz',
  'Straße',
  'Hausnummer',
  'Hausnummerergänzung',
  'PLZ',
  'Ort',
  'Land',
  'VM_Vorname',
  'VM_Nachname',
  'VM_Firma',
  'VM_Straße',
  'VM_Hausnummer',
  'VM_Hausnummerergänzung',
  'VM_PLZ',
  'VM_Ort',
  'VM_Geburtsdatum',
  'VM_Änderung',
  'LS Vorname ',
  'LS Nachname',
  'LS Firma',
  'LS-Namenszusatz',
  'Lieferstellenbezeichnung',
  'LS Straße',
  'LS Hausnummer',
  'LS Hausnummerergänzung',
  'LS PLZ',
  'LS Ort',
  'LS Bundesland',
  'Kostenstelle',
  'Vormieter',
  'Umgezogen von',
  'Zählernummer',
  'MaLo-ID',
  'MeLo-ID',
  'Verbrauch kWh/a HT',
  'Verbrauch kWh/a NT',
  'Zählverfahren',
  'Abschlag',
  'Abschlagsplan',
  'bisherige Jahresmaximalleistung',
  'Zähleranfang (HT)',
  'Zähleranfang (NT)',
  'Ablesedatum',
  'Ableseart',
  'Konzessionsabgabe',
  'Konzessionsabgabe Betrag (€/kWh)',
  'Konzessionsabgabe Schwachlast',
  'Konzessionsabgabe Betrag SL (€/kWh)',
  'Gemeinderabatt (in%)',
  'bisheriger Lieferant',
  'Kundennummer bei Altlieferant',
  'Verteilnetzbetreiber',
  'Handelsvertreter / VM Nr.',
  'ID Berater',
  'Partner',
  'Ramenvertragskunde',
  'Umsatzsteuer-ID',
  'Erlaubnisschein Nr.',
  'Steuerliche Bewertung',
  'DVK Nr.',
  'VA-Nr.',
  'Ordercode',
  'vermittelt durch',
  'Geworbener Identnummer',
  'Geworbener Prämie/Bonus in Euro',
  'Geworbener Prämie/Bonus in kWh',
  'Geworbener Sachprämie',
  'Geworbener Termin der Auszahlung Prämie/Bonus',
  'Geworbener Prämienart',
  'Geworbener Auszahlungsdatum',
  'Werber Identnummer',
  'Werber Prämie/Bonus in Euro',
  'Werber Prämie/Bonus in kWh',
  'Werber Sachprämie',
  'Werber Termin der Auszahlung Prämie/Bonus',
  'Werber Prämienart',
  'Werber Auszahlungsdatum',
  'Bemerkung Prämie',
  'Werbung',
  'Kategorie bei NN',
  'Kundengruppe',
  'Ansprechpartner Vertrieb',
  'Abrechnungszeitpunkt',
  'Abrechnungsplan',
  'Zahlungsziel Abrechnung',
  'Bemerkung',
  'T-ID',
  'Partner',
  'gültig_ab',
  'gültig_bis',
  'Preisgarantie bis (Datum)',
  'Preisgarantie in Monate',
  'Bezeichnung_extern',
  'Bezeichnung_intern',
  'Tarifart',
  'monatlicher Grundpreis netto',
  'Arbeitspreis_HT excl. Stromsteuer und USt',
  'Arbeitspreis_NT excl. Stromsteuer und USt',
  'Grundpreis Netznutzung/netto',
  'Arbeitspreis_HT Netznutzung/netto',
  'Arbeitspreis_NT Netznutzung/netto',
  'Abrechnungspreis',
  'Messpreis',
  'Messstellenbetrieb',
  'Stromsteuer_HT',
  'Stromsteuer_NT',
  'USt %',
  'Kaution',
  'Gebührenart',
  'Gebühr',
  'EEG ct/kWh',
  'Abschaltbare Lasten ct/kWh',
  'KWKG ct/kWh',
  'NEV_Umlage ct/kWh',
  'Offshore Netzumlage ct/kWh',
  'Konzessionsabgabe_HT',
  'Konzessionsabgabe_Zone_HT',
  'Konzessionsabgabe_HT gezont',
  'Konzessionsabgabe_NT',
  'Konzessionsabgabe_Zone_NT',
  'Konzessionsabgabe_NT gezont',
  'Mindestvertragslaufzeit',
  'Folgelaufzeit in Monaten einmalig',
  'Folgelaufzeit in Monaten regelmäßig',
  'Kündigungsfrist',
  'Bemerkung / Tarifstaffel / Info / Freifeld',
  'Leistungspreis_monatlich',
  'Leistungspreis_jährlich',
  'Blindmehrarbeit',
  'HT-Staffel 1 von kWh',
  'HT-Staffel 1 bis kWh',
  'HT-Staffel 1 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 1 ct/kWh netto ohne USt',
  'HT-Staffel 2 von kWh',
  'HT-Staffel 2 bis kWh',
  'HT-Staffel 2 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 2 ct/kWh netto ohne USt',
  'HT-Staffel 3 von kWh',
  'HT-Staffel 3 bis kWh',
  'HT-Staffel 3 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 3 ct/kWh netto ohne USt',
  'HT-Staffel 4 von kWh',
  'HT-Staffel 4 bis kWh',
  'HT-Staffel 4 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 4 ct/kWh netto ohne USt',
  'HT-Staffel 5 von kWh',
  'HT-Staffel 5 bis kWh',
  'HT-Staffel 5 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 5 ct/kWh netto ohne USt',
  'HT-Staffel 6 von kWh',
  'HT-Staffel 6 bis kWh',
  'HT-Staffel 6 Festpreis Euro/Jahr ohne USt',
  'HT-Staffel 6 ct/kWh netto ohne USt',
  'HT-Staffel 7 von kWh',
  'HT-Staffel 7 bis kWh',
  'HT-Staffel 7 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 7 ct/kWh netto ohne USt',
  'HT-Staffel 8 von kWh',
  'HT-Staffel 8 bis kWh',
  'HT-Staffel 8 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 8 ct/kWh netto ohne USt',
  'HT-Staffel 9 von kWh',
  'HT-Staffel 9 bis kWh',
  'HT-Staffel 9 Festpreis  Euro/Jahr ohne USt',
  'HT-Staffel 9 ct/kWh netto ohne USt',
  'NT-Staffel 1 von kWh',
  'NT-Staffel 1 bis kWh',
  'NT-Staffel 1 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 1 ct/kWh netto ohne USt',
  'NT-Staffel 2 von kWh',
  'NT-Staffel 2 bis kWh',
  'NT-Staffel 2 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 2 ct/kWh netto ohne USt',
  'NT-Staffel 3 von kWh',
  'NT-Staffel 3 bis kWh',
  'NT-Staffel 3 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 3 ct/kWh netto ohne USt',
  'NT-Staffel 4 von kWh',
  'NT-Staffel 4 bis kWh',
  'NT-Staffel 4 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 4 ct/kWh netto ohne USt',
  'NT-Staffel 5 von kWh',
  'NT-Staffel 5 bis kWh',
  'NT-Staffel 5 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 5 ct/kWh netto ohne USt',
  'NT-Staffel 6 von kWh',
  'NT-Staffel 6 bis kWh',
  'NT-Staffel 6 Festpreis Euro/Jahr ohne USt',
  'NT-Staffel 6 ct/kWh netto ohne USt',
  'NT-Staffel 7 von kWh',
  'NT-Staffel 7 bis kWh',
  'NT-Staffel 7 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 7 ct/kWh netto ohne USt',
  'NT-Staffel 8 von kWh',
  'NT-Staffel 8 bis kWh',
  'NT-Staffel 8 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 8 ct/kWh netto ohne USt',
  'NT-Staffel 9 von kWh',
  'NT-Staffel 9 bis kWh',
  'NT-Staffel 9 Festpreis  Euro/Jahr ohne USt',
  'NT-Staffel 9 ct/kWh netto ohne USt',
  'Zonenpreise ja/nein',
];
