export default [
  'Transaktionsgrund',
  'Einzugsdatum',
  'Vertragsbindung bei Vorlieferant',
  'Wunschtermin',
  'Datum Vertragseingang',
  'Typ Vertrag',
  'Kunde zahlt Netznutzung',
  'Bilanzkreis',
  'Master-ID/Vertragspartner',
  'MK VIP',
  'MK Firma',
  'MK c/o bei Firma',
  'MK Briefanrede',
  'MK Anrede',
  'MK Titel',
  'MK Vorname',
  'MK Nachname',
  'MK Anrede2',
  'MK Titel2',
  'MK Vorname2',
  'MK Nachname2',
  'MK Geburtstag',
  'MK Geburtstag2',
  'MK Straße',
  'MK Hausnummer',
  'MK Hausnummerergänzung',
  'MK Postleitzahl',
  'MK Ort',
  'MK Land',
  'MK Telefon privat',
  'MK Fax',
  'MK Telefon geschäftlich',
  'MK Handy',
  'MK E-Mailadresse',
  'MK Login',
  'MK Passwort',
  'MK Kontoinhaber',
  'MK Bank',
  'MK BIC',
  'MK IBAN',
  'MK Mandat-Nr.',
  'MK Datum Unterschrift',
  'MK einmalige Zahlung',
  'MK Firmenmandat',
  'MK elektronisches Mandat',
  'MK Selbstzahler',
  'MK Zahlungstermin',
  'MK Zusätzlicher DTA Verwendungszweck',
  'MK Anrede Zahler',
  'MK Titel Zahler',
  'MK Vorname Zahler',
  'MK Nachname Zahler',
  'MK Firma Zahler',
  'MK c/o Zusatz Zahler',
  'MK Straße Zahler',
  'MK Hausnummer Zahler',
  'MK Hausnummerergänzung Zahler',
  'MK PLZ Zahler',
  'MK Ort Zahler',
  'MK Land Zahler',
  'MK Telefon Privat Zahler',
  'MK Telefon geschäftlich Zahler',
  'MK Mobil Zahler',
  'MK Fax Zahler',
  'MK E-Mail Zahler',
  'Schreiben an Masterkunden adressieren (postalisch)',
  'Schreiben an MP elektronisch',
  'Abschläge und Verbräuche summieren',
  'Abschläge auch bei untergeordneten Kunden buchen',
  'Abschläge sind nur bei untergeordnetem Kunden abbuchbar',
  'MK Abschlagsplan',
  'RA Identnummer',
  'RA Master_ID',
  'VIP',
  'RA Firma',
  'RA c/o bei Firma',
  'RA Briefanrede',
  'RA Anrede',
  'RA Titel',
  'RA Vorname',
  'RA Nachname',
  'RA Anrede2',
  'RA Titel2',
  'RA Vorname2',
  'RA Nachname2',
  'RA Geburtstag',
  'RA Geburtstag2',
  'RA Straße',
  'RA Hausnummer',
  'RA Hausnummerergänzung',
  'RA Postleitzahl',
  'RA Ort',
  'RA Land',
  'RA Telefon privat',
  'RA Fax',
  'RA Telefon geschäftlich',
  'RA Mobil',
  'RA E-Mailadresse',
  'RA Login',
  'RA Passwort',
  'Interne ID',
  'Versandart',
  'RA Kontoinhaber',
  'RA Bank',
  'RA BIC',
  'RA IBAN',
  'RA Mandat-Nr.',
  'RA Datum Unterschrift',
  'RA einmalige Zahlung',
  'RA Firmenmandat',
  'RA elektronisches Mandat',
  'RA Selbstzahler',
  'RA Zahlungstermin',
  'RA Zusätzlicher DTA Verwendungszweck',
  'RA Anrede Zahler',
  'RA Titel Zahler',
  'RA Vorname Zahler',
  'RA Nachname Zahler',
  'RA Firma Zahler',
  'RA c/o Zusatz Zahler',
  'RA Straße Zahler',
  'RA Hausnummer Zahler',
  'RA Hausnummerergänzung Zahler',
  'RA PLZ Zahler',
  'RA Ort Zahler',
  'RA Land Zahler',
  'RA Telefon Privat Zahler',
  'RA Telefon geschäftlich Zahler',
  'RA Mobil Zahler',
  'RA Fax Zahler',
  'RA E-Mail Zahler',
  'Firma',
  'c/o Zusatz',
  'Straße',
  'Hausnummer',
  'Hausnummerergänzung',
  'PLZ',
  'Ort',
  'Land',
  'LS Vorname ',
  'LS Nachname',
  'LS Firma',
  'LS-Namenszusatz',
  'Lieferstellenbezeichnung',
  'LS Straße',
  'LS Hausnummer',
  'LS Hausnummerergänzung',
  'LS PLZ',
  'LS Ort',
  'LS Bundesland',
  'Kostenstelle',
  'Vormieter',
  'Umgezogen von',
  'Zählernummer',
  'MaLo-ID (- Neu Version S4.2)',
  'MeLo-ID (- Neu Version S4.2)',
  'Verbrauch kWh/a HT',
  'Verbrauch kWh/a NT',
  'Kundenwert',
  'Zählverfahren',
  'SVK Messspannung',
  'SVK Lieferspannung',
  'Abschlag',
  'Abschlagsplan',
  'bisherige Jahresmaximalleistung',
  'Zähleranfang (HT)',
  'Zähleranfang (NT)',
  'Ablesedatum',
  'Ableseart',
  'Konzessionsabgabe',
  'Konzessionsabgabe Betrag (€/kWh)',
  'Konzessionsabgabe Schwachlast',
  'Konzessionsabgabe Betrag SL (€/kWh)',
  'Gemeinderabatt (in%)',
  'bisheriger Lieferant',
  'Kundennummer bei Altlieferant',
  'Grundversorger',
  'Verteilnetzbetreiber',
  'Regelzone/Marktgebiet',
  'Handelsvertreter / VM Nr.',
  'ID Berater',
  'Partner',
  'Ramenvertragskunde',
  'DVK Nr.',
  'VA-Nr.',
  'Ordercode',
  'vermittelt durch',
  'Geworbener Identnummer (- Neu Version S4.2)',
  'Geworbener Prämie/Bonus in Euro',
  'Geworbener Prämie/Bonus in kWh',
  'Geworbener Sachprämie',
  'Geworbener Termin der Auszahlung Prämie/Bonus',
  'Geworbener Prämienart (- Neu Version S4.2)',
  'Geworbener Auszahlungsdatum (- Neu Version S4.2)',
  'Werber Identnummer',
  'Werber Prämie/Bonus in Euro',
  'Werber Prämie/Bonus in kWh',
  'Werber Sachprämie',
  'Werber Termin der Auszahlung Prämie/Bonus',
  'Werber Prämienart (- Neu Version S4.2)',
  'Werber Auszahlungsdatum (- Neu Version S4.2)',
  'Bemerkung Prämie (- Neu Version S4.2)',
  'Werbung',
  'Kategorie bei NN',
  'Kundengruppe',
  'Ansprechpartner Vertrieb',
  'Abrechnungszeitpunkt',
  'Abrechnungsplan',
  'Zahlungsziel Abrechnung (- Neu Version S4.2)',
  'Bemerkung',
  'T-ID',
  'Partner',
  'gültig_ab',
  'gültig_bis',
  'Preisgarantie bis (Datum)',
  'Preisgarantie in Monate',
  'Bezeichnung_extern',
  'Bezeichnung_intern',
  'Tarifart',
  'monatlicher Grundpreis netto',
  'Arbeitspreis_HT excl. Stromsteuer und USt',
  'Arbeitspreis_NT excl. Stromsteuer und USt',
  'Grundpreis Netznutzung/netto',
  'Arbeitspreis_HT Netznutzung/netto',
  'Arbeitspreis_NT Netznutzung/netto',
  'Abrechnungspreis',
  'Messpreis',
  'Messstellenbetrieb',
  'Stromsteuer_HT',
  'Stromsteuer_NT',
  'USt %',
  'Kaution',
  'Gebührenart',
  'Gebühr',
  'EEG ct/kWh',
  'Abschaltbare Lasten ct/kWh',
  'KWKG ct/kWh',
  'NEV_Umlage ct/kWh',
  'Offshore Haftungsumlage ct/kWh',
  'Konzessionsabgabe_HT',
  'Zone',
  'Konzessionsabgabe_HT gezont',
  'Konzessionsabgabe_NT',
  'Zone',
  'Konzessionsabgabe_NT gezont',
  'Mindestvertragslaufzeit',
  'Folgelaufzeit in Monaten einmalig',
  'Folgelaufzeit in Monaten regelmäßig',
  'Kündigungsfrist',
  'Bemerkung / Tarifstaffel / Info / Freifeld',
  'Leistungspreis_monatlich',
  'Leistungspreis_jährlich',
  'Blindmehrarbeit',
  'HT-Staffel 1 von kWh',
  'HT-Staffel 1 bis kWh',
  'Staffel 1 Festpreis Euro/Jahr ohne USt',
  'Staffel 1 ct/kWh netto o. UST',
  'HT-Staffel 2 von kWh',
  'HT-Staffel 2 bis kWh',
  'Staffel 2 Festpreis  Euro/Jahr ohne USt',
  'Staffel 2 ct/kWh netto o. UST',
  'HT-Staffel 3 von kWh',
  'HT-Staffel 3 bis kWh',
  'Staffel 3 Festpreis  Euro/Jahr ohne USt',
  'Staffel 3 ct/kWh netto o. UST',
  'HT-Staffel 4 von kWh',
  'HT-Staffel 4 bis kWh',
  'Staffel 4 Festpreis Euro/Jahr ohne USt',
  'Staffel 4 ct/kWh netto o. UST',
  'HT-Staffel 5 von kWh',
  'HT-Staffel 5 bis kWh',
  'Staffel 5 Festpreis Euro/Jahr ohne USt',
  'Staffel 5 ct/kWh netto o. UST',
  'HT-Staffel 6 von kWh',
  'HT-Staffel 6 bis kWh',
  'Staffel 6 Festpreis Euro/Jahr ohne USt',
  'Staffel 6 ct/kWh netto o. UST',
  'HT-Staffel 7 von kWh',
  'HT-Staffel 7 bis kWh',
  'Staffel 7 Festpreis  Euro/Jahr ohne USt',
  'Staffel 7 ct/kWh netto o. UST',
  'HT-Staffel 8 von kWh',
  'HT-Staffel 8 bis kWh',
  'Staffel 8 Festpreis  Euro/Jahr ohne USt',
  'Staffel 8 ct/kWh netto o. UST',
  'HT-Staffel 9 von kWh',
  'HT-Staffel 9 bis kWh',
  'Staffel 9 Festpreis  Euro/Jahr ohne USt',
  'Staffel 9 ct/kWh netto o. UST',
  'NT-Staffel 1 von kWh',
  'NT-Staffel 1 bis kWh',
  'Staffel 1 Festpreis Euro/Jahr ohne USt',
  'Staffel 1 ct/kWh netto o. UST',
  'NT-Staffel 2 von kWh',
  'NT-Staffel 2 bis kWh',
  'Staffel 2 Festpreis  Euro/Jahr ohne USt',
  'Staffel 2 ct/kWh netto o. UST',
  'NT-Staffel 3 von kWh',
  'NT-Staffel 3 bis kWh',
  'Staffel 3 Festpreis  Euro/Jahr ohne USt',
  'Staffel 3 ct/kWh netto o. UST',
  'NT-Staffel 4 von kWh',
  'NT-Staffel 4 bis kWh',
  'Staffel 4 Festpreis Euro/Jahr ohne USt',
  'Staffel 4 ct/kWh netto o. UST',
  'NT-Staffel 5 von kWh',
  'NT-Staffel 5 bis kWh',
  'Staffel 5 Festpreis Euro/Jahr ohne USt',
  'Staffel 5 ct/kWh netto o. UST',
  'NT-Staffel 6 von kWh',
  'NT-Staffel 6 bis kWh',
  'Staffel 6 Festpreis Euro/Jahr ohne USt',
  'Staffel 6 ct/kWh netto o. UST',
  'NT-Staffel 7 von kWh',
  'NT-Staffel 7 bis kWh',
  'Staffel 7 Festpreis  Euro/Jahr ohne USt',
  'Staffel 7 ct/kWh netto o. UST',
  'NT-Staffel 8 von kWh',
  'NT-Staffel 8 bis kWh',
  'Staffel 8 Festpreis  Euro/Jahr ohne USt',
  'Staffel 8 ct/kWh netto o. UST',
  'NT-Staffel 9 von kWh',
  'NT-Staffel 9 bis kWh',
  'Staffel 9 Festpreis  Euro/Jahr ohne USt',
  'Staffel 9 ct/kWh netto o. UST',
  'Zonenpreise ja/nein',
];
