// flow-typed signature: bc170276b1cec1ffbb6e0cc0a4a4a175
// flow-typed version: <<STUB>>/buzzn-style_vgit://github.com/buzzn/buzzn-style.git/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buzzn-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buzzn-style' {
  declare module.exports: any;
}
