// flow-typed signature: 02dce81bc5b3d8e626f40a1aa4a58648
// flow-typed version: <<STUB>>/buzzn-style_vgit://github.com/buzzn/buzzn-style.git/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buzzn-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buzzn-style' {
  declare module.exports: any;
}
