// flow-typed signature: c94c89c2676b88cfbeca671d960c261e
// flow-typed version: <<STUB>>/react-component-managers_v^3.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-component-managers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-component-managers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-component-managers/lib/autoFocus' {
  declare module.exports: any;
}

declare module 'react-component-managers/lib/focusManager' {
  declare module.exports: any;
}

declare module 'react-component-managers/lib/index' {
  declare module.exports: any;
}

declare module 'react-component-managers/lib/mixin' {
  declare module.exports: any;
}

declare module 'react-component-managers/lib/mountManager' {
  declare module.exports: any;
}

declare module 'react-component-managers/lib/timeoutManager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-component-managers/lib/autoFocus.js' {
  declare module.exports: $Exports<'react-component-managers/lib/autoFocus'>;
}
declare module 'react-component-managers/lib/focusManager.js' {
  declare module.exports: $Exports<'react-component-managers/lib/focusManager'>;
}
declare module 'react-component-managers/lib/index.js' {
  declare module.exports: $Exports<'react-component-managers/lib/index'>;
}
declare module 'react-component-managers/lib/mixin.js' {
  declare module.exports: $Exports<'react-component-managers/lib/mixin'>;
}
declare module 'react-component-managers/lib/mountManager.js' {
  declare module.exports: $Exports<'react-component-managers/lib/mountManager'>;
}
declare module 'react-component-managers/lib/timeoutManager.js' {
  declare module.exports: $Exports<'react-component-managers/lib/timeoutManager'>;
}
