// flow-typed signature: e281298e89296f6f1780d2725c9d93e8
// flow-typed version: <<STUB>>/@buzzn/i18n_vgit+https://github.com/buzzn/i18n.git/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@buzzn/i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@buzzn/i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@buzzn/i18n/dist/admin/de' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/addresses' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/bank_accounts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/contracts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/formulas' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/meters' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/organizations' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/payments' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/persons' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/readings' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/registers' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/tariffs' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/de/types' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/addresses' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/bank_accounts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/contracts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/formulas' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/meters' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/organizations' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/payments' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/persons' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/readings' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/registers' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/tariffs' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/admin/en/types' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/index' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/module_powertaker_form/de' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/dist/module_powertaker_form/en' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/addresses' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/bank_accounts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/contracts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/formulas' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/meters' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/organizations' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/payments' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/persons' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/readings' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/registers' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/tariffs' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/de/types' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/addresses' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/bank_accounts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/contracts' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/formulas' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/meters' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/organizations' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/payments' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/persons' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/readings' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/registers' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/tariffs' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/admin/en/types' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/index' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/module_powertaker_form/de' {
  declare module.exports: any;
}

declare module '@buzzn/i18n/frontend/module_powertaker_form/en' {
  declare module.exports: any;
}

// Filename aliases
declare module '@buzzn/i18n/dist/admin/de.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de'>;
}
declare module '@buzzn/i18n/dist/admin/de/addresses.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/addresses'>;
}
declare module '@buzzn/i18n/dist/admin/de/bank_accounts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/bank_accounts'>;
}
declare module '@buzzn/i18n/dist/admin/de/contracts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/contracts'>;
}
declare module '@buzzn/i18n/dist/admin/de/formulas.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/formulas'>;
}
declare module '@buzzn/i18n/dist/admin/de/meters.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/meters'>;
}
declare module '@buzzn/i18n/dist/admin/de/organizations.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/organizations'>;
}
declare module '@buzzn/i18n/dist/admin/de/payments.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/payments'>;
}
declare module '@buzzn/i18n/dist/admin/de/persons.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/persons'>;
}
declare module '@buzzn/i18n/dist/admin/de/readings.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/readings'>;
}
declare module '@buzzn/i18n/dist/admin/de/registers.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/registers'>;
}
declare module '@buzzn/i18n/dist/admin/de/tariffs.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/tariffs'>;
}
declare module '@buzzn/i18n/dist/admin/de/types.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/de/types'>;
}
declare module '@buzzn/i18n/dist/admin/en.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en'>;
}
declare module '@buzzn/i18n/dist/admin/en/addresses.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/addresses'>;
}
declare module '@buzzn/i18n/dist/admin/en/bank_accounts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/bank_accounts'>;
}
declare module '@buzzn/i18n/dist/admin/en/contracts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/contracts'>;
}
declare module '@buzzn/i18n/dist/admin/en/formulas.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/formulas'>;
}
declare module '@buzzn/i18n/dist/admin/en/meters.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/meters'>;
}
declare module '@buzzn/i18n/dist/admin/en/organizations.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/organizations'>;
}
declare module '@buzzn/i18n/dist/admin/en/payments.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/payments'>;
}
declare module '@buzzn/i18n/dist/admin/en/persons.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/persons'>;
}
declare module '@buzzn/i18n/dist/admin/en/readings.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/readings'>;
}
declare module '@buzzn/i18n/dist/admin/en/registers.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/registers'>;
}
declare module '@buzzn/i18n/dist/admin/en/tariffs.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/tariffs'>;
}
declare module '@buzzn/i18n/dist/admin/en/types.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/admin/en/types'>;
}
declare module '@buzzn/i18n/dist/index.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/index'>;
}
declare module '@buzzn/i18n/dist/module_powertaker_form/de.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/module_powertaker_form/de'>;
}
declare module '@buzzn/i18n/dist/module_powertaker_form/en.js' {
  declare module.exports: $Exports<'@buzzn/i18n/dist/module_powertaker_form/en'>;
}
declare module '@buzzn/i18n/frontend/admin/de.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de'>;
}
declare module '@buzzn/i18n/frontend/admin/de/addresses.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/addresses'>;
}
declare module '@buzzn/i18n/frontend/admin/de/bank_accounts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/bank_accounts'>;
}
declare module '@buzzn/i18n/frontend/admin/de/contracts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/contracts'>;
}
declare module '@buzzn/i18n/frontend/admin/de/formulas.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/formulas'>;
}
declare module '@buzzn/i18n/frontend/admin/de/meters.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/meters'>;
}
declare module '@buzzn/i18n/frontend/admin/de/organizations.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/organizations'>;
}
declare module '@buzzn/i18n/frontend/admin/de/payments.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/payments'>;
}
declare module '@buzzn/i18n/frontend/admin/de/persons.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/persons'>;
}
declare module '@buzzn/i18n/frontend/admin/de/readings.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/readings'>;
}
declare module '@buzzn/i18n/frontend/admin/de/registers.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/registers'>;
}
declare module '@buzzn/i18n/frontend/admin/de/tariffs.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/tariffs'>;
}
declare module '@buzzn/i18n/frontend/admin/de/types.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/de/types'>;
}
declare module '@buzzn/i18n/frontend/admin/en.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en'>;
}
declare module '@buzzn/i18n/frontend/admin/en/addresses.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/addresses'>;
}
declare module '@buzzn/i18n/frontend/admin/en/bank_accounts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/bank_accounts'>;
}
declare module '@buzzn/i18n/frontend/admin/en/contracts.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/contracts'>;
}
declare module '@buzzn/i18n/frontend/admin/en/formulas.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/formulas'>;
}
declare module '@buzzn/i18n/frontend/admin/en/meters.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/meters'>;
}
declare module '@buzzn/i18n/frontend/admin/en/organizations.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/organizations'>;
}
declare module '@buzzn/i18n/frontend/admin/en/payments.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/payments'>;
}
declare module '@buzzn/i18n/frontend/admin/en/persons.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/persons'>;
}
declare module '@buzzn/i18n/frontend/admin/en/readings.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/readings'>;
}
declare module '@buzzn/i18n/frontend/admin/en/registers.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/registers'>;
}
declare module '@buzzn/i18n/frontend/admin/en/tariffs.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/tariffs'>;
}
declare module '@buzzn/i18n/frontend/admin/en/types.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/admin/en/types'>;
}
declare module '@buzzn/i18n/frontend/index.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/index'>;
}
declare module '@buzzn/i18n/frontend/module_powertaker_form/de.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/module_powertaker_form/de'>;
}
declare module '@buzzn/i18n/frontend/module_powertaker_form/en.js' {
  declare module.exports: $Exports<'@buzzn/i18n/frontend/module_powertaker_form/en'>;
}
