// flow-typed signature: 67a6a6ef4bd06284af077731eb26723e
// flow-typed version: <<STUB>>/@buzzn/module_charts_vgit+https://github.com/buzzn/module-charts.git#v2.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@buzzn/module_charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@buzzn/module_charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@buzzn/module_charts/app/actions' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/api' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/components/chart_layout' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/components/chart_wrapper' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/components/chart' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/configure_store' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/index.dev' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/index' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/reducers' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/root' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/sagas' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/tests/util.tests' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/util/chart_config' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/app/util/process_data' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/actions' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/api' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/components/chart_layout' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/components/chart_wrapper' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/components/chart' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/configure_store' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/index.dev' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/index' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/reducers' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/root' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/sagas' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/tests/util.tests' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/util/chart_config' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/dist/util/process_data' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/postcss.config' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/tests-setup' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/webpack.config' {
  declare module.exports: any;
}

declare module '@buzzn/module_charts/webpack.production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@buzzn/module_charts/app/actions.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/actions'>;
}
declare module '@buzzn/module_charts/app/api.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/api'>;
}
declare module '@buzzn/module_charts/app/components/chart_layout.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/components/chart_layout'>;
}
declare module '@buzzn/module_charts/app/components/chart_wrapper.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/components/chart_wrapper'>;
}
declare module '@buzzn/module_charts/app/components/chart.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/components/chart'>;
}
declare module '@buzzn/module_charts/app/configure_store.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/configure_store'>;
}
declare module '@buzzn/module_charts/app/index.dev.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/index.dev'>;
}
declare module '@buzzn/module_charts/app/index.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/index'>;
}
declare module '@buzzn/module_charts/app/reducers.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/reducers'>;
}
declare module '@buzzn/module_charts/app/root.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/root'>;
}
declare module '@buzzn/module_charts/app/sagas.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/sagas'>;
}
declare module '@buzzn/module_charts/app/tests/util.tests.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/tests/util.tests'>;
}
declare module '@buzzn/module_charts/app/util/chart_config.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/util/chart_config'>;
}
declare module '@buzzn/module_charts/app/util/process_data.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/app/util/process_data'>;
}
declare module '@buzzn/module_charts/dist/actions.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/actions'>;
}
declare module '@buzzn/module_charts/dist/api.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/api'>;
}
declare module '@buzzn/module_charts/dist/components/chart_layout.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/components/chart_layout'>;
}
declare module '@buzzn/module_charts/dist/components/chart_wrapper.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/components/chart_wrapper'>;
}
declare module '@buzzn/module_charts/dist/components/chart.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/components/chart'>;
}
declare module '@buzzn/module_charts/dist/configure_store.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/configure_store'>;
}
declare module '@buzzn/module_charts/dist/index.dev.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/index.dev'>;
}
declare module '@buzzn/module_charts/dist/index.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/index'>;
}
declare module '@buzzn/module_charts/dist/reducers.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/reducers'>;
}
declare module '@buzzn/module_charts/dist/root.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/root'>;
}
declare module '@buzzn/module_charts/dist/sagas.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/sagas'>;
}
declare module '@buzzn/module_charts/dist/tests/util.tests.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/tests/util.tests'>;
}
declare module '@buzzn/module_charts/dist/util/chart_config.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/util/chart_config'>;
}
declare module '@buzzn/module_charts/dist/util/process_data.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/dist/util/process_data'>;
}
declare module '@buzzn/module_charts/postcss.config.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/postcss.config'>;
}
declare module '@buzzn/module_charts/tests-setup.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/tests-setup'>;
}
declare module '@buzzn/module_charts/webpack.config.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/webpack.config'>;
}
declare module '@buzzn/module_charts/webpack.production.config.js' {
  declare module.exports: $Exports<'@buzzn/module_charts/webpack.production.config'>;
}
