// flow-typed signature: 5f06d614bf7256a1f1528d835d5563bf
// flow-typed version: <<STUB>>/@buzzn/module_auth_vgit+https://github.com/buzzn/module-auth.git#v2.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@buzzn/module_auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@buzzn/module_auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@buzzn/module_auth/app/__mocks__/fileMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/actions' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/api' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/components/password_sign_in' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/components/sign_out_button' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/constants' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/index' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/reducers' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/sagas' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/tests/actions.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/tests/reducers.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/app/tests/sagas.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/__mocks__/fileMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/actions' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/api' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/components/password_sign_in' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/components/sign_out_button' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/constants' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/index' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/reducers' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/sagas' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/tests/actions.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/tests/reducers.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/dist/tests/sagas.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/postcss.config' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/webpack.config' {
  declare module.exports: any;
}

declare module '@buzzn/module_auth/webpack.production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@buzzn/module_auth/app/__mocks__/fileMock.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/__mocks__/fileMock'>;
}
declare module '@buzzn/module_auth/app/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/__mocks__/styleMock'>;
}
declare module '@buzzn/module_auth/app/actions.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/actions'>;
}
declare module '@buzzn/module_auth/app/api.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/api'>;
}
declare module '@buzzn/module_auth/app/components/password_sign_in.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/components/password_sign_in'>;
}
declare module '@buzzn/module_auth/app/components/sign_out_button.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/components/sign_out_button'>;
}
declare module '@buzzn/module_auth/app/constants.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/constants'>;
}
declare module '@buzzn/module_auth/app/index.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/index'>;
}
declare module '@buzzn/module_auth/app/reducers.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/reducers'>;
}
declare module '@buzzn/module_auth/app/sagas.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/sagas'>;
}
declare module '@buzzn/module_auth/app/tests/actions.test.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/tests/actions.test'>;
}
declare module '@buzzn/module_auth/app/tests/reducers.test.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/tests/reducers.test'>;
}
declare module '@buzzn/module_auth/app/tests/sagas.test.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/app/tests/sagas.test'>;
}
declare module '@buzzn/module_auth/dist/__mocks__/fileMock.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/__mocks__/fileMock'>;
}
declare module '@buzzn/module_auth/dist/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/__mocks__/styleMock'>;
}
declare module '@buzzn/module_auth/dist/actions.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/actions'>;
}
declare module '@buzzn/module_auth/dist/api.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/api'>;
}
declare module '@buzzn/module_auth/dist/components/password_sign_in.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/components/password_sign_in'>;
}
declare module '@buzzn/module_auth/dist/components/sign_out_button.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/components/sign_out_button'>;
}
declare module '@buzzn/module_auth/dist/constants.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/constants'>;
}
declare module '@buzzn/module_auth/dist/index.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/index'>;
}
declare module '@buzzn/module_auth/dist/reducers.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/reducers'>;
}
declare module '@buzzn/module_auth/dist/sagas.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/sagas'>;
}
declare module '@buzzn/module_auth/dist/tests/actions.test.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/tests/actions.test'>;
}
declare module '@buzzn/module_auth/dist/tests/reducers.test.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/tests/reducers.test'>;
}
declare module '@buzzn/module_auth/dist/tests/sagas.test.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/dist/tests/sagas.test'>;
}
declare module '@buzzn/module_auth/postcss.config.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/postcss.config'>;
}
declare module '@buzzn/module_auth/webpack.config.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/webpack.config'>;
}
declare module '@buzzn/module_auth/webpack.production.config.js' {
  declare module.exports: $Exports<'@buzzn/module_auth/webpack.production.config'>;
}
