// flow-typed signature: b27a51ace876459a790f9dfd19e25bd0
// flow-typed version: <<STUB>>/@buzzn/module_bubbles_vgit+https://github.com/buzzn/module-bubbles.git#27_visibility/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@buzzn/module_bubbles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@buzzn/module_bubbles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@buzzn/module_bubbles/app/__mocks__/fileMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/_util' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/actions' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/api' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/components/bubbles_layout' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/components/bubbles_wrapper' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/components/bubbles' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/configure_store' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/index.dev' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/index' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/reducers' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/root' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/sagas' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/app/tests/actions.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/__mocks__/fileMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/_util' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/actions' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/api' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/components/bubbles_layout' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/components/bubbles_wrapper' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/components/bubbles' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/configure_store' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/index.dev' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/index' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/reducers' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/root' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/sagas' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/dist/tests/actions.test' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/postcss.config' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/webpack.config' {
  declare module.exports: any;
}

declare module '@buzzn/module_bubbles/webpack.production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@buzzn/module_bubbles/app/__mocks__/fileMock.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/__mocks__/fileMock'>;
}
declare module '@buzzn/module_bubbles/app/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/__mocks__/styleMock'>;
}
declare module '@buzzn/module_bubbles/app/_util.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/_util'>;
}
declare module '@buzzn/module_bubbles/app/actions.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/actions'>;
}
declare module '@buzzn/module_bubbles/app/api.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/api'>;
}
declare module '@buzzn/module_bubbles/app/components/bubbles_layout.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/components/bubbles_layout'>;
}
declare module '@buzzn/module_bubbles/app/components/bubbles_wrapper.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/components/bubbles_wrapper'>;
}
declare module '@buzzn/module_bubbles/app/components/bubbles.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/components/bubbles'>;
}
declare module '@buzzn/module_bubbles/app/configure_store.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/configure_store'>;
}
declare module '@buzzn/module_bubbles/app/index.dev.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/index.dev'>;
}
declare module '@buzzn/module_bubbles/app/index.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/index'>;
}
declare module '@buzzn/module_bubbles/app/reducers.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/reducers'>;
}
declare module '@buzzn/module_bubbles/app/root.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/root'>;
}
declare module '@buzzn/module_bubbles/app/sagas.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/sagas'>;
}
declare module '@buzzn/module_bubbles/app/tests/actions.test.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/app/tests/actions.test'>;
}
declare module '@buzzn/module_bubbles/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/coverage/lcov-report/prettify'>;
}
declare module '@buzzn/module_bubbles/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/coverage/lcov-report/sorter'>;
}
declare module '@buzzn/module_bubbles/dist/__mocks__/fileMock.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/__mocks__/fileMock'>;
}
declare module '@buzzn/module_bubbles/dist/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/__mocks__/styleMock'>;
}
declare module '@buzzn/module_bubbles/dist/_util.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/_util'>;
}
declare module '@buzzn/module_bubbles/dist/actions.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/actions'>;
}
declare module '@buzzn/module_bubbles/dist/api.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/api'>;
}
declare module '@buzzn/module_bubbles/dist/components/bubbles_layout.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/components/bubbles_layout'>;
}
declare module '@buzzn/module_bubbles/dist/components/bubbles_wrapper.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/components/bubbles_wrapper'>;
}
declare module '@buzzn/module_bubbles/dist/components/bubbles.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/components/bubbles'>;
}
declare module '@buzzn/module_bubbles/dist/configure_store.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/configure_store'>;
}
declare module '@buzzn/module_bubbles/dist/index.dev.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/index.dev'>;
}
declare module '@buzzn/module_bubbles/dist/index.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/index'>;
}
declare module '@buzzn/module_bubbles/dist/reducers.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/reducers'>;
}
declare module '@buzzn/module_bubbles/dist/root.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/root'>;
}
declare module '@buzzn/module_bubbles/dist/sagas.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/sagas'>;
}
declare module '@buzzn/module_bubbles/dist/tests/actions.test.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/dist/tests/actions.test'>;
}
declare module '@buzzn/module_bubbles/postcss.config.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/postcss.config'>;
}
declare module '@buzzn/module_bubbles/webpack.config.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/webpack.config'>;
}
declare module '@buzzn/module_bubbles/webpack.production.config.js' {
  declare module.exports: $Exports<'@buzzn/module_bubbles/webpack.production.config'>;
}
